In [1]:
import numpy as np

flowers = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
print(flowers)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [16]:
import numpy as np

flowers1 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
flowers1[2][2]

55

In [26]:
# here is selected last two lists in a 3d array
import numpy as np
flowers2 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
flowers2[1 : 3]

array([[25, 30, 35, 40],
       [45, 50, 55, 60]])

In [29]:
# select a particular colum in a 3d array. Here " :4 "is a column which i want is select and 3 is the lists which this includes
#note the ":" this comes before the column you have selected and then mention the list's that is 3
import numpy as np
flowers3 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
flowers3[:4, 3]

array([20, 40, 60])

In [41]:
# boolean indexing
# the answer here shows the places of the numbers which get divisible by 5
import numpy as np
flowers4 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
print(flowers4)
x  = flowers4[flowers4 % 5 == 0]
# x = np.where(flowers4 % 5 == 0)
print(x)


[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[ 5 10 15 20 25 30 35 40 45 50 55 60]


In [36]:
# finding even numbers
import numpy as np
a = np.arange(1, 50)
a = a[a%2==0]
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [38]:
# finding numbers less than a given value

import numpy as np
flowers5 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
more = flowers5[flowers5 <= 55]
print(more)

[ 5 10 15 20 25 30 35 40 45 50 55]


In [40]:
#using ~ (it tries to do things opposite)

import numpy as np
flowers6 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
new = flowers6 < 50
flowers6[~new]

array([50, 55, 60])

In [48]:
# replacing the numbers in an provided if they satisfy given condition

import numpy as np
flowers7 = np.array([[5, 10, 15, 20], [25, 30, 35, 40], [45, 50, 55, 60]])
z  = flowers7 % 3 == 0
print(z)

print(flowers7)

SyntaxError: invalid syntax (<ipython-input-48-515620e2f403>, line 7)

In [62]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

a = exercises[locations == "outside"]
print(a)





['running' 'hiking']


In [64]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

b = exercises[(locations == "outside") & (minutes < 30)]
print(b)

[]


In [67]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

c = minutes[exercises == "basketball"]
print(c)

[45]


In [68]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

d = exercises[minutes == 45]
print(d)

['gymnastics' 'basketball']


In [70]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

e = exercises[minutes < 30]
print(e)

[]


In [74]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

f = exercises[(locations == "inside") & (minutes == 45)]
print(f)

['gymnastics' 'basketball']


In [77]:
import numpy as np
exercises = np.array(["running", "gymnastics", "basketball", "weights","hiking"])
locations = np.array(["outside", "inside", "inside", "inside", "outside"])
minutes = np.array([30, 45, 45, 30, 60])

g = exercises[minutes >= 60 ]
print(g)

['hiking']


In [78]:
# where any clause
import numpy as np

rents = np.array([1250, 800, 750, 775, 1100, 1150, 1250, 750])
low_rent = np.where(rents < 1000)
print(low_rent)


(array([1, 2, 3, 7], dtype=int64),)


In [84]:
# Any clause its 
import numpy as np

rents = np.array([1250, 800, 750, 775, 1100, 1150, 1250, 750])
check = np.any(rents == 1250, axis = 0)
print(check)



True


In [85]:
# All clause
import numpy as np

rents = np.array([1250, 800, 750, 775, 1100, 1150, 1250, 750])
what_we_got = np.all(rents > 500, axis = 0)
print(what_we_got)

True


In [86]:
#Fancy index

import numpy as np
x = np.array([9, 0, 95, 84, 65, 52, 44, 73, 6, 20])
inx = [7, 5, 8, 1]
print(x[inx])

[73 52  6  0]
